### ISSUE TITLE
Allow ContractRejectionMessage as ErrorResponse

### ISSUE THREAD

**Issue by tmberthold** [FraunhoferISST/IDS-Connector-Framework#1]
Copied from the old GitLab project (created by @juliapampus):

![image](https://user-images.githubusercontent.com/75306992/104596735-a8049600-5674-11eb-8c5a-173f513d267b.png)

**Comment by tmberthold** [comment]
After a quick view: The builder methods of the infomodel return by type an interface, but we expect the implementation of the interface as parameter in the ErrorResponse create-method. Will take a closer look.

Due to the generic typing in the BodyResponse class, this does not lead to a problem there, because the Interface returned by the Builder extends the Message-Type in a roundabout way.

**Comment by vdakker** [comment]
In [Version 4.0.1](https://github.com/FraunhoferISST/IDS-Connector-Framework/releases/tag/4.0.1) `ErrorMessage` accepts the generic `RejectionMessage` interface instead of `RejectionMessageImpl` so other subtypes can be used as an `ErrorMessage`.
